// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cloudwego/eino/components/tool"
	"github.com/mark3labs/mcp-go/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEinoMcpClient creates a new instance of MockEinoMcpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEinoMcpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEinoMcpClient {
	mock := &MockEinoMcpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEinoMcpClient is an autogenerated mock type for the EinoMcpClient type
type MockEinoMcpClient struct {
	mock.Mock
}

type MockEinoMcpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEinoMcpClient) EXPECT() *MockEinoMcpClient_Expecter {
	return &MockEinoMcpClient_Expecter{mock: &_m.Mock}
}

// CallTool provides a mock function for the type MockEinoMcpClient
func (_mock *MockEinoMcpClient) CallTool(ctx context.Context, name string, args map[string]any) (*mcp.CallToolResult, error) {
	ret := _mock.Called(ctx, name, args)

	if len(ret) == 0 {
		panic("no return value specified for CallTool")
	}

	var r0 *mcp.CallToolResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) (*mcp.CallToolResult, error)); ok {
		return returnFunc(ctx, name, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) *mcp.CallToolResult); ok {
		r0 = returnFunc(ctx, name, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.CallToolResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, name, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEinoMcpClient_CallTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallTool'
type MockEinoMcpClient_CallTool_Call struct {
	*mock.Call
}

// CallTool is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args map[string]any
func (_e *MockEinoMcpClient_Expecter) CallTool(ctx interface{}, name interface{}, args interface{}) *MockEinoMcpClient_CallTool_Call {
	return &MockEinoMcpClient_CallTool_Call{Call: _e.mock.On("CallTool", ctx, name, args)}
}

func (_c *MockEinoMcpClient_CallTool_Call) Run(run func(ctx context.Context, name string, args map[string]any)) *MockEinoMcpClient_CallTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEinoMcpClient_CallTool_Call) Return(callToolResult *mcp.CallToolResult, err error) *MockEinoMcpClient_CallTool_Call {
	_c.Call.Return(callToolResult, err)
	return _c
}

func (_c *MockEinoMcpClient_CallTool_Call) RunAndReturn(run func(ctx context.Context, name string, args map[string]any) (*mcp.CallToolResult, error)) *MockEinoMcpClient_CallTool_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockEinoMcpClient
func (_mock *MockEinoMcpClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEinoMcpClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEinoMcpClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEinoMcpClient_Expecter) Close() *MockEinoMcpClient_Close_Call {
	return &MockEinoMcpClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEinoMcpClient_Close_Call) Run(run func()) *MockEinoMcpClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEinoMcpClient_Close_Call) Return(err error) *MockEinoMcpClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEinoMcpClient_Close_Call) RunAndReturn(run func() error) *MockEinoMcpClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// EinoTools provides a mock function for the type MockEinoMcpClient
func (_mock *MockEinoMcpClient) EinoTools(ctx context.Context, filter []mcp.Tool) ([]tool.BaseTool, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for EinoTools")
	}

	var r0 []tool.BaseTool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mcp.Tool) ([]tool.BaseTool, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mcp.Tool) []tool.BaseTool); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tool.BaseTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []mcp.Tool) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEinoMcpClient_EinoTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EinoTools'
type MockEinoMcpClient_EinoTools_Call struct {
	*mock.Call
}

// EinoTools is a helper method to define mock.On call
//   - ctx context.Context
//   - filter []mcp.Tool
func (_e *MockEinoMcpClient_Expecter) EinoTools(ctx interface{}, filter interface{}) *MockEinoMcpClient_EinoTools_Call {
	return &MockEinoMcpClient_EinoTools_Call{Call: _e.mock.On("EinoTools", ctx, filter)}
}

func (_c *MockEinoMcpClient_EinoTools_Call) Run(run func(ctx context.Context, filter []mcp.Tool)) *MockEinoMcpClient_EinoTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []mcp.Tool
		if args[1] != nil {
			arg1 = args[1].([]mcp.Tool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEinoMcpClient_EinoTools_Call) Return(baseTools []tool.BaseTool, err error) *MockEinoMcpClient_EinoTools_Call {
	_c.Call.Return(baseTools, err)
	return _c
}

func (_c *MockEinoMcpClient_EinoTools_Call) RunAndReturn(run func(ctx context.Context, filter []mcp.Tool) ([]tool.BaseTool, error)) *MockEinoMcpClient_EinoTools_Call {
	_c.Call.Return(run)
	return _c
}

// ListTools provides a mock function for the type MockEinoMcpClient
func (_mock *MockEinoMcpClient) ListTools(ctx context.Context) ([]mcp.Tool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTools")
	}

	var r0 []mcp.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]mcp.Tool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []mcp.Tool); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mcp.Tool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEinoMcpClient_ListTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTools'
type MockEinoMcpClient_ListTools_Call struct {
	*mock.Call
}

// ListTools is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEinoMcpClient_Expecter) ListTools(ctx interface{}) *MockEinoMcpClient_ListTools_Call {
	return &MockEinoMcpClient_ListTools_Call{Call: _e.mock.On("ListTools", ctx)}
}

func (_c *MockEinoMcpClient_ListTools_Call) Run(run func(ctx context.Context)) *MockEinoMcpClient_ListTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEinoMcpClient_ListTools_Call) Return(tools []mcp.Tool, err error) *MockEinoMcpClient_ListTools_Call {
	_c.Call.Return(tools, err)
	return _c
}

func (_c *MockEinoMcpClient_ListTools_Call) RunAndReturn(run func(ctx context.Context) ([]mcp.Tool, error)) *MockEinoMcpClient_ListTools_Call {
	_c.Call.Return(run)
	return _c
}
