// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mark3labs/mcp-go/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMcpClient creates a new instance of MockMcpClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMcpClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMcpClient {
	mock := &MockMcpClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMcpClient is an autogenerated mock type for the McpClient type
type MockMcpClient struct {
	mock.Mock
}

type MockMcpClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMcpClient) EXPECT() *MockMcpClient_Expecter {
	return &MockMcpClient_Expecter{mock: &_m.Mock}
}

// CallTool provides a mock function for the type MockMcpClient
func (_mock *MockMcpClient) CallTool(ctx context.Context, name string, args map[string]any) (*mcp.CallToolResult, error) {
	ret := _mock.Called(ctx, name, args)

	if len(ret) == 0 {
		panic("no return value specified for CallTool")
	}

	var r0 *mcp.CallToolResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) (*mcp.CallToolResult, error)); ok {
		return returnFunc(ctx, name, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) *mcp.CallToolResult); ok {
		r0 = returnFunc(ctx, name, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.CallToolResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, name, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMcpClient_CallTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallTool'
type MockMcpClient_CallTool_Call struct {
	*mock.Call
}

// CallTool is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args map[string]any
func (_e *MockMcpClient_Expecter) CallTool(ctx interface{}, name interface{}, args interface{}) *MockMcpClient_CallTool_Call {
	return &MockMcpClient_CallTool_Call{Call: _e.mock.On("CallTool", ctx, name, args)}
}

func (_c *MockMcpClient_CallTool_Call) Run(run func(ctx context.Context, name string, args map[string]any)) *MockMcpClient_CallTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMcpClient_CallTool_Call) Return(callToolResult *mcp.CallToolResult, err error) *MockMcpClient_CallTool_Call {
	_c.Call.Return(callToolResult, err)
	return _c
}

func (_c *MockMcpClient_CallTool_Call) RunAndReturn(run func(ctx context.Context, name string, args map[string]any) (*mcp.CallToolResult, error)) *MockMcpClient_CallTool_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockMcpClient
func (_mock *MockMcpClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMcpClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMcpClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMcpClient_Expecter) Close() *MockMcpClient_Close_Call {
	return &MockMcpClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMcpClient_Close_Call) Run(run func()) *MockMcpClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMcpClient_Close_Call) Return(err error) *MockMcpClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMcpClient_Close_Call) RunAndReturn(run func() error) *MockMcpClient_Close_Call {
	_c.Call.Return(run)
	return _c
}
